Repository flexflow/flexflow-train, pull requests merged in 2023-08, with the labels that each got.

#893 Python interface for inference (part 2)
  CMakeLists.txt
  FlexFlow.mk
  INSTALL.md
  include/flexflow/ffconst.h
  include/flexflow/flexflow_c.h
  inference/file_loader.cc
  inference/flexflow_inference.py
  inference/incr_decoding/incr_decoding.cc
  inference/models/falcon.cc
  inference/models/opt.cc
  inference/python/incr_decoding.py
  inference/python/spec_infer.py
  inference/utils/download_opt_weights.py
  python/flexflow/core/flexflow_cffi.py
  python/flexflow/serve/__init__.py
  python/flexflow/serve/models/base.py
  python/flexflow/serve/models/falcon.py
  python/flexflow/serve/models/llama.py
  python/flexflow/serve/models/opt.py
  python/flexflow/serve/serve.py
  python/flexflow/type.py
  python/flexflow_python_build.py
  src/c/flexflow_c.cc
  src/ops/argmax.cc
  src/ops/fused.cu
  src/runtime/model.cc
  src/runtime/request_manager.cc
  tests/inference/cpp_inference_tests.sh
  tests/inference_tests.sh
Labels: inference

#898 Ci update
  .clang-tidy-15
  .github/workflows/clang-format-check.yml
  lib/utils/include/utils/test_types.h
  scripts/format.sh
Labels: repo-refactor

#936 Deploy to `pip`
  .github/workflows/pip-deploy.yml
Labels: inference

#962 starcoder model.
  include/flexflow/ffconst.h
  include/flexflow/flexflow_c.h
  include/flexflow/model.h
  include/flexflow/request_manager.h
  inference/file_loader.cc
  inference/incr_decoding/CMakeLists.txt
  inference/incr_decoding/incr_decoding.cc
  inference/models/opt.cc
  inference/models/starcoder.cc
  inference/models/starcoder.h
  python/flexflow/core/flexflow_cffi.py
  python/flexflow/serve/models/__init__.py
  python/flexflow/serve/models/opt.py
  python/flexflow/serve/models/starcoder.py
  python/flexflow/serve/serve.py
  python/flexflow/type.py
  src/c/flexflow_c.cc
  src/ops/inc_multihead_self_attention.cu
  src/runtime/inference_manager.cc
  src/runtime/request_manager.cc
  src/runtime/request_manager.cu
  tests/inference/cpp_inference_tests.sh
  tests/inference/python_test_configs/generate_configs.py
Labels: inference

#960 New README.md for FlexFlow Serve
  .github/README.md
  .github/workflows/gpu-ci.yml
  conda/flexflow.yml
  img/performance.png
  requirements.txt
Labels: inference

#966 Fix CUDA Error in the sampling operator
  include/flexflow/flexflow_c.h
  include/flexflow/inference.h
  inference/incr_decoding/incr_decoding.cc
  inference/models/llama.cc
  inference/models/llama.h
  inference/models/starcoder.cc
  inference/models/starcoder.h
  inference/python/incr_decoding.py
  inference/python/spec_infer.py
  inference/spec_infer/spec_infer.cc
  python/flexflow/core/flexflow_cffi.py
  python/flexflow/serve/__init__.py
  python/flexflow/serve/models/base.py
  python/flexflow/serve/models/falcon.py
  python/flexflow/serve/models/llama.py
  python/flexflow/serve/models/opt.py
  python/flexflow/serve/models/starcoder.py
  python/flexflow/serve/serve.py
  src/c/flexflow_c.cc
  src/ops/linear.cc
  src/ops/sampling.cc
  src/runtime/request_manager.cc
  tests/inference/python_test_configs/generate_configs.py
Labels: inference

#870 add unit tests for compiler
  lib/compiler/include/compiler/machine_mapping.h
  lib/compiler/include/compiler/unity_algorithm.h
  lib/compiler/src/graph_utils.h
  lib/compiler/src/machine_mapping.cc
  lib/compiler/src/unity_algorithm.cc
  lib/compiler/test/test_cost_estimator.h
  lib/compiler/test/test_generator.h
  lib/compiler/test/test_machine_mapping.cc
  lib/compiler/test/test_optimal_cost.cc
  lib/compiler/test/test_unity_algorithm.cc
  lib/utils/include/utils/bidict.h
  lib/utils/include/utils/containers.h
  lib/utils/include/utils/graph/cow_ptr_t.h
  lib/utils/include/utils/graph/labelled/views.h
  lib/utils/include/utils/graph/serialparallel.h
  lib/utils/include/utils/test_types.h
  lib/utils/src/graph/serialparallel.cc
Labels: repo-refactor

#890 Add first draft of docs for visitable
  lib/utils/README.md
Labels: repo-refactor

#886 Build Attention and Aggregate Spec
  lib/kernels/include/kernels/allocation.h
  lib/kernels/include/kernels/attention_kernels.h
  lib/op-attrs/src/attention.cc
  lib/runtime/include/runtime/task_spec/typed_task_invocation.h
  lib/runtime/src/ops/aggregate_spec.cc
  lib/runtime/src/ops/attention.cc
  lib/runtime/src/ops/attention.h
  lib/runtime/src/ops/batch_matmul.cc
  lib/runtime/src/ops/batch_norm.cc
  lib/runtime/src/ops/cast.cc
  lib/runtime/src/ops/concat.cc
  lib/runtime/src/ops/conv_2d.cc
  lib/runtime/src/optimizer.h
  lib/runtime/src/realm_allocator.cc
  lib/runtime/src/realm_allocator.h
  lib/runtime/src/sim_environment.h
  lib/runtime/src/task_spec/arg_ref.h
  lib/runtime/src/task_spec/device_specific_arg.h
  lib/runtime/src/task_spec/op_arg_ref.h
  lib/runtime/src/task_spec/op_task_invocation.h
  lib/runtime/src/task_spec/op_task_signature.h
  lib/runtime/src/task_spec/runtime_arg_ref.cc
  lib/runtime/src/task_spec/runtime_arg_ref.h
  lib/runtime/src/task_spec/task_argument_accessor.h
  lib/utils/include/utils/visitable.h
Labels: repo-refactor

#1004 Support loading local model
  python/flexflow/serve/serve.py
Labels: inference

#958 Fixes #906. Capture variables in lambda by copy.
  src/ops/attention.cc
  src/ops/batch_norm.cc
  src/ops/concat.cc
  src/ops/dropout.cc
  src/ops/element_binary.cc
  src/ops/element_unary.cc
  src/ops/flat.cc
  src/ops/layer_norm.cc
  src/ops/linear.cc
  src/ops/reduce.cc
  src/ops/reverse.cc
Labels: bug

#1015 Added missing iterator include
  lib/utils/include/utils/type_traits_core.h
Labels: repo-refactor

#1009 Rename DeviceSpecificArg to DeviceSpecific
  lib/runtime/src/legion_backing.cc
  lib/runtime/src/ops/aggregate_spec.cc
  lib/runtime/src/ops/attention.cc
  lib/runtime/src/task_spec/device_specific.h
  lib/runtime/src/task_spec/op_arg_ref.h
  lib/runtime/src/task_spec/runtime_arg_ref.cc
  lib/runtime/src/task_spec/runtime_arg_ref.h
  lib/runtime/src/task_spec/task_argument_accessor.h
Labels: repo-refactor
