Repository flexflow/flexflow-train, pull requests merged in 2023-10, with the labels that each got.

#1018 Make MAX_BATCH_SIZE, MAX_NUM_TOKENS, MAX_SEQ_LENGTH user-provided input arguments
  include/flexflow/batch_config.h
  include/flexflow/flexflow_c.h
  include/flexflow/request_manager.h
  inference/incr_decoding/incr_decoding.cc
  inference/models/falcon.cc
  inference/models/falcon.h
  inference/models/llama.cc
  inference/models/llama.h
  inference/models/mpt.cc
  inference/models/mpt.h
  inference/models/opt.cc
  inference/models/opt.h
  inference/models/starcoder.cc
  inference/models/starcoder.h
  inference/python/incr_decoding.py
  inference/python/spec_infer.py
  inference/spec_infer/spec_infer.cc
  python/flexflow/core/flexflow_cffi.py
  python/flexflow/serve/models/base.py
  python/flexflow/serve/models/falcon.py
  python/flexflow/serve/models/llama.py
  python/flexflow/serve/models/mpt.py
  python/flexflow/serve/models/opt.py
  python/flexflow/serve/models/starcoder.py
  python/flexflow/serve/serve.py
  src/c/flexflow_c.cc
  src/ops/beam_topk.cpp
  src/ops/beam_topk.cu
  src/ops/inc_multihead_self_attention.cc
  src/ops/inc_multihead_self_attention.cpp
  src/ops/inc_multihead_self_attention.cu
  src/ops/spec_inc_multihead_self_attention.cpp
  src/ops/spec_inc_multihead_self_attention.cu
  src/ops/tree_inc_multihead_self_attention.cpp
  src/ops/tree_inc_multihead_self_attention.cu
  src/runtime/batch_config.cc
  src/runtime/beam_search_batch_config.cc
  src/runtime/inference_manager.cc
  src/runtime/model.cc
  src/runtime/request_manager.cc
  src/runtime/request_manager.cpp
  src/runtime/request_manager.cu
  src/runtime/tree_verify_batch_config.cc
Labels: inference

#1139 No Op Op
  lib/pcg/include/pcg/layer.h
  lib/runtime/src/operator.h
  lib/runtime/src/ops/noop.cc
  lib/runtime/src/ops/noop.h
  lib/runtime/src/task_spec/op_task_signature.h
  lib/utils/include/utils/fmt.h
  lib/utils/include/utils/stack_string.h
  lib/utils/include/utils/stack_vector.h
Labels: repo-refactor

#1114 Concat Op
  lib/kernels/include/kernels/concat_kernels.h
  lib/kernels/src/cuda/concat_kernels.cu
  lib/op-attrs/include/op-attrs/ops/concat.h
  lib/runtime/include/runtime/config.h
  lib/runtime/src/ops/concat.cc
  lib/runtime/src/ops/concat.h
  lib/runtime/src/serialization.h
  lib/runtime/src/task_spec/op_task_invocation.h
  lib/runtime/src/task_spec/op_tensor_spec.h
  lib/runtime/src/task_spec/runtime_arg_ref.h
  lib/runtime/src/task_spec/variadic_tensor_ref.h
Labels: repo-refactor

#1169 Finish conv2d op
  lib/runtime/src/ops/conv_2d.cc
Labels: repo-refactor

#1113 Combine Op
  lib/kernels/include/kernels/combine_kernels.h
  lib/kernels/src/cuda/combine_kernels.cu
  lib/runtime/src/ops/combine.cc
  lib/runtime/src/ops/combine.h
Labels: repo-refactor

#1136 Element Binary
  lib/kernels/include/kernels/element_binary_kernels.h
  lib/kernels/src/cuda/element_binary_kernels.cu
  lib/runtime/src/ops/element_binary.cc
  lib/runtime/src/ops/element_binary.h
Labels: repo-refactor, op-refactor

#1134 Dropout Op
  lib/kernels/include/kernels/dropout_kernels.h
  lib/kernels/src/cuda/dropout_kernels.cu
  lib/kernels/src/hip/dropout_kernels.cpp
  lib/runtime/src/ops/dropout.cc
  lib/runtime/src/ops/dropout.h
Labels: repo-refactor, op-refactor

#1137 Flat Operator
  lib/kernels/include/kernels/flat_kernels.h
  lib/kernels/src/cuda/flat_kernels.cu
  lib/kernels/src/hip/flat_kernels.cpp
  lib/runtime/src/ops/flat.cc
  lib/runtime/src/ops/flat.h
Labels: repo-refactor, op-refactor

#1110 Batch Norm Op
  lib/kernels/include/kernels/batch_norm_kernels.h
  lib/kernels/src/cuda/batch_norm_kernels.cu
  lib/kernels/src/hip/batch_norm_kernels.cpp
  lib/runtime/src/ops/batch_norm.cc
  lib/runtime/src/ops/batch_norm.h
Labels: repo-refactor, op-refactor

#1177 Purge MOE operators
  bindings/python/python/flexflow/op_attrs/raw.py
  lib/kernels/include/kernels/aggregate_kernels.h
  lib/kernels/include/kernels/aggregate_spec_kernels.h
  lib/kernels/include/kernels/groupby_kernels.h
  lib/kernels/src/cuda/aggregate_kernels.cu
  lib/kernels/src/cuda/aggregate_spec_kernels.cu
  lib/kernels/src/cuda/group_by_kernels.cu
  lib/kernels/src/hip/aggregate_kernels.cpp
  lib/kernels/src/hip/aggregate_spec_kernels.cpp
  lib/kernels/src/hip/group_by_kernels.cpp
  lib/op-attrs/ffi/include/flexflow/op-attrs.h
  lib/op-attrs/include/op-attrs/get_op_type.h
  lib/op-attrs/include/op-attrs/get_output_shapes.h
  lib/op-attrs/include/op-attrs/op.h
  lib/op-attrs/include/op-attrs/operator_attrs.h
  lib/op-attrs/include/op-attrs/ops/aggregate.h
  lib/op-attrs/include/op-attrs/ops/aggregate_spec.h
  lib/op-attrs/include/op-attrs/ops/groupby.h
  lib/op-attrs/src/aggregate.cc
  lib/op-attrs/src/aggregate_spec.cc
  lib/op-attrs/src/get_op_type.cc
  lib/op-attrs/src/get_output_shapes.cc
  lib/op-attrs/src/groupby.cc
  lib/op-attrs/src/operator_attrs.cc
  lib/pcg/ffi/include/flexflow/pcg.h
  lib/pcg/include/pcg/computation_graph_builder.h
  lib/pcg/src/computation_graph_builder.cc
  lib/runtime/src/ops/aggregate.cc
  lib/runtime/src/ops/aggregate.h
  lib/runtime/src/ops/aggregate_spec.cc
  lib/runtime/src/ops/aggregate_spec.h
  lib/runtime/src/ops/group_by.cc
  lib/runtime/src/ops/groupby.h
  lib/runtime/src/ops/moe.cc
  lib/runtime/src/task_spec.cc
  lib/runtime/src/tasks.cc
  lib/runtime/src/tasks.h
  lib/runtime/test/src/test_serialization.cc
  lib/substitutions/include/substitutions/get_attribute.h
  lib/substitutions/include/substitutions/serialization.h
  lib/substitutions/src/operator_attributes.cc
Labels: repo-refactor, op-refactor

#1111 Cast Op
  lib/kernels/include/kernels/cast_kernels.h
  lib/kernels/src/cuda/cast_kernels.cu
  lib/kernels/src/hip/cast_kernels.cpp
  lib/runtime/src/ops/cast.cc
  lib/runtime/src/ops/cast.h
Labels: repo-refactor, op-refactor

#1106 SoftMax OP
  lib/kernels/include/kernels/softmax_kernels.h
  lib/kernels/src/cuda/softmax_kernels.cu
  lib/runtime/src/ops/softmax.cc
  lib/runtime/src/ops/softmax.h
Labels: repo-refactor, op-refactor

#1101 Replicate OP
  lib/runtime/src/ops/replicate.cc
  lib/runtime/src/ops/replicate.h
Labels: repo-refactor, op-refactor

#1042 Pre-build Legion library
  .github/workflows/helpers/prebuild_legion.sh
  .github/workflows/prebuild-legion.yml
  CMakeLists.txt
  cmake/cuda.cmake
  config/config.inc
  config/config.linux
  docker/build.sh
  docker/flexflow-environment/Dockerfile
  docker/flexflow/Dockerfile
Labels: enhancement

#1117 Transpose OP
  lib/kernels/include/kernels/transpose_kernels.h
  lib/kernels/src/cuda/transpose_kernels.cu
  lib/op-attrs/include/op-attrs/get_output_shapes.h
  lib/runtime/src/ops/transpose.cc
  lib/runtime/src/ops/transpose.h
Labels: repo-refactor, op-refactor

#1116 topK OP
  lib/kernels/include/kernels/topk_kernels.h
  lib/kernels/src/cuda/topk_kernels.cu
  lib/runtime/src/ops/topk.cc
  lib/runtime/src/ops/topk.h
Labels: repo-refactor, op-refactor
