Repository flexflow/flexflow-train, pull requests merged in 2023-07, with the labels that each got.

#828 Label Chart Elements
  lib/utils/include/utils/graph/README.md
Labels: repo-refactor

#834 Fix `cuda_fp16.h` not found issue
  cmake/cuda.cmake
  lib/utils/CMakeLists.txt
Labels: repo-refactor

#845 [Inference] - Save output of inference test as an artifact
  .github/workflows/gpu-ci.yml
  tests/inference_tests.sh
Labels: inference

#857 fixup: always disable hijack
  src/runtime/simulator.cpp
  src/runtime/simulator.cu
Labels: bug

#841 add opt 13B config
  inference/models/configs/opt_13B.json
Labels: inference

#862 Generalize Containers.h
  lib/utils/include/utils/containers.h
  lib/utils/include/utils/stack_map.h
  lib/utils/include/utils/stack_vector.h
  lib/utils/include/utils/type_traits.h
Labels: repo-refactor

#854 Inference: Sampling result
  include/flexflow/ffconst.h
  include/flexflow/inference.h
  include/flexflow/model.h
  include/flexflow/operator_params.h
  include/flexflow/ops/sampling.h
  include/flexflow/ops/sampling_params.h
  inference/incr_decoding/incr_decoding.cc
  inference/models/llama.cc
  inference/models/llama.h
  inference/spec_infer/spec_infer.cc
  src/ops/fused.cu
  src/ops/sampling.cc
  src/ops/sampling.cpp
  src/ops/sampling.cu
  src/runtime/ffconst_utils.cc
  src/runtime/graph.cc
  src/runtime/model.cc
  src/runtime/operator_params.cc
Labels: inference

#837 update new models weights
  inference/utils/download_llama_weights.py
Labels: inference

#863 Inference: fix batch_size issue.
  include/flexflow/batch_config.h
Labels: inference

#878 Python interface for inference
  include/flexflow/flexflow_c.h
  include/flexflow/inference.h
  include/flexflow/model.h
  inference/flexflow_inference.py
  inference/incr_decoding/incr_decoding.cc
  inference/models/llama.cc
  inference/models/opt.cc
  inference/spec_infer/spec_infer.cc
  python/flexflow/core/flexflow_cffi.py
  python/flexflow/serve/__init__.py
  python/flexflow/serve/models/__init__.py
  python/flexflow/serve/models/falcon.py
  python/flexflow/serve/models/llama.py
  python/flexflow/serve/models/opt.py
  python/flexflow/serve/serve.py
  python/flexflow/type.py
  src/c/flexflow_c.cc
  src/ops/element_binary.cc
  src/runtime/inference_manager.cc
Labels: inference

#877 fix compile errors from filter and support_interator_tag
  lib/utils/include/utils/containers.h
  lib/utils/include/utils/type_traits.h
  lib/utils/include/utils/type_traits_core.h
Labels: repo-refactor

#865 Improve required implementation and some graph fixes for compiler.
  .clang-format-15
  .clang-tidy-15
  lib/compiler/include/compiler/cost_estimate.h
  lib/compiler/include/compiler/machine_mapping.h
  lib/compiler/include/compiler/sub_parallel_computation_graph.h
  lib/compiler/include/compiler/unity_algorithm.h
  lib/compiler/src/graph_utils.cc
  lib/compiler/src/machine_mapping.cc
  lib/compiler/test/test_open_graph.cc
  lib/op-attrs/include/op-attrs/parallel_dim.h
  lib/pcg/ffi/include/flexflow/pcg.h
  lib/runtime/src/realm_allocator.cc
  lib/utils/README.md
  lib/utils/include/utils/containers.h
  lib/utils/include/utils/graph/algorithms.h
  lib/utils/include/utils/graph/labelled/algorithms.h
  lib/utils/include/utils/graph/labelled/labelled_downward_open.h
  lib/utils/include/utils/graph/labelled/labelled_downward_open_interfaces.h
  lib/utils/include/utils/graph/labelled/labelled_open.h
  lib/utils/include/utils/graph/labelled/labelled_open_interfaces.h
  lib/utils/include/utils/graph/labelled/labelled_upward_open.h
  lib/utils/include/utils/graph/labelled/labelled_upward_open_interfaces.h
  lib/utils/include/utils/graph/labelled/open_algorithms.h
  lib/utils/include/utils/graph/labelled/open_views.h
  lib/utils/include/utils/graph/labelled/output_labelled.h
  lib/utils/include/utils/graph/labelled/standard_labelled.h
  lib/utils/include/utils/graph/labelled/views.h
  lib/utils/include/utils/graph/labelled_graphs.h
  lib/utils/include/utils/graph/multidigraph_interfaces.h
  lib/utils/include/utils/graph/open_graph_interfaces.h
  lib/utils/include/utils/graph/query_set.h
  lib/utils/include/utils/graph/serialparallel.h
  lib/utils/include/utils/graph/undirected.h
  lib/utils/include/utils/graph/views.h
  lib/utils/include/utils/required.h
  lib/utils/include/utils/required_core.h
  lib/utils/include/utils/strong_typedef.h
  lib/utils/include/utils/test_types.h
  lib/utils/include/utils/type_traits.h
  lib/utils/include/utils/type_traits_core.h
  lib/utils/include/utils/variant.h
  lib/utils/include/utils/visitable.h
  lib/utils/include/utils/visitable_core.h
  lib/utils/src/graph/algorithms.cc
  lib/utils/src/graph/serialparallel.cc
  lib/utils/src/graph/undirected.cc
Labels: repo-refactor

#889 Fix fusion bug
  src/ops/fused.cu
  tests/inference_tests.sh
Labels: inference

#888 Inference: add argmax operator
  include/flexflow/ffconst.h
  include/flexflow/model.h
  include/flexflow/operator_params.h
  include/flexflow/ops/argmax.h
  include/flexflow/ops/argmax_params.h
  inference/models/llama.cc
  inference/models/opt.cc
  src/ops/argmax.cc
  src/ops/argmax.cpp
  src/ops/argmax.cu
  src/runtime/cuda_helper.cu
  src/runtime/ffconst_utils.cc
  src/runtime/graph.cc
  src/runtime/model.cc
  src/runtime/operator_params.cc
Labels: inference

#891 [Docker] - Make it easier to attach inference weights to docker
  docker/run.sh
Labels: inference

#876 Fix container name in GPU CI tests
  .github/workflows/gpu-ci.yml
  .github/workflows/multinode-test.yml
Labels: bug

#896 change argmax to DeviceSegmentedReduce::ArgMax && replace cudamalloc with legion instance
  include/flexflow/ops/argmax.h
  include/flexflow/ops/beam_topk.h
  include/flexflow/ops/kernels/linear_kernels.h
  include/flexflow/ops/kernels/rms_norm_kernels.h
  include/flexflow/ops/layer_norm.h
  include/flexflow/ops/rms_norm.h
  include/flexflow/ops/sampling.h
  include/flexflow/simulator.h
  src/ops/argmax.cc
  src/ops/argmax.cpp
  src/ops/argmax.cu
  src/ops/beam_topk.cc
  src/ops/beam_topk.cpp
  src/ops/beam_topk.cu
  src/ops/kernels/linear_kernels.cpp
  src/ops/kernels/linear_kernels.cu
  src/ops/kernels/rms_norm_kernels.cpp
  src/ops/kernels/rms_norm_kernels.cu
  src/ops/layer_norm.cc
  src/ops/layer_norm.cpp
  src/ops/layer_norm.cu
  src/ops/rms_norm.cc
  src/ops/sampling.cc
  src/ops/sampling.cpp
  src/ops/sampling.cu
Labels: inference

#895 Allow passing parameters to `config.linux`
  config/config.linux
Labels: enhancement
